# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secretar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretar_name', models.CharField(max_length=100)),
                ('secretar_number', models.CharField(max_length=15)),
                ('secretar_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_numner', models.CharField(max_length=15)),
                ('student_name', models.CharField(max_length=200)),
                ('student_surname', models.CharField(max_length=200)),
                ('student_phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
