# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0004_new_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
