# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0005_game_archives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game_archives',
        ),
        migrations.DeleteModel(
            name='New_game',
        ),
    ]
