# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0006_auto_20170217_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('register_date', models.DateTimeField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('otkoruu_jeri', models.TextField()),
            ],
        ),
    ]
