# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0007_new_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_game',
            new_name='Active_game',
        ),
    ]
