# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0008_auto_20170217_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='st_register_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
