# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0012_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_game',
            name='sport',
            field=models.ManyToManyField(to='spartakiada.Sport'),
        ),
    ]
