# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0015_student_st_fac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spartakiada.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_f_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spartakiada.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Uchastniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('pers_num', models.CharField(max_length=20)),
                ('admin_f_s_id', models.ManyToManyField(to='spartakiada.Admin_f_s')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='st_fac',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
