# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0016_auto_20170302_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secretar',
        ),
    ]
