# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0020_auto_20170304_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_f_s',
            name='is_true',
            field=models.NullBooleanField(),
        ),
    ]
