# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0021_admin_f_s_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_f',
            name='faculty_id',
        ),
        migrations.DeleteModel(
            name='Admin_f',
        ),
    ]
