# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0022_auto_20170328_0301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uchastniki',
            new_name='Participants',
        ),
    ]
