# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0023_auto_20170411_0226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_f_s',
            new_name='User_f',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='admin_f_s_id',
            new_name='user_f_id',
        ),
    ]
