# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spartakiada', '0024_auto_20170424_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_f',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_f',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_f',
            name='surname',
        ),
        migrations.AddField(
            model_name='user_f',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_f',
            name='is_true',
            field=models.NullBooleanField(default=False),
        ),
    ]
