# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0025_auto_20170424_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_f',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
