# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0026_auto_20170424_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_f',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='user_f',
            name='sport_id',
        ),
        migrations.RemoveField(
            model_name='user_f',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='user_f_id',
        ),
        migrations.DeleteModel(
            name='User_f',
        ),
    ]
