# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spartakiada', '0027_auto_20170424_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_true', models.BooleanField(default=False)),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spartakiada.Faculty')),
                ('sport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spartakiada.Sport')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='user_f_id',
            field=models.ManyToManyField(to='spartakiada.User_f'),
        ),
    ]
