# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0028_auto_20170424_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='depart',
        ),
        migrations.AddField(
            model_name='participants',
            name='depart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spartakiada.Faculty'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='user_f_id',
            field=models.ManyToManyField(null=True, to='spartakiada.User_f'),
        ),
        migrations.AlterField(
            model_name='user_f',
            name='is_true',
            field=models.NullBooleanField(default=False),
        ),
    ]
