# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0029_auto_20170425_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='user_f_id',
        ),
        migrations.AddField(
            model_name='participants',
            name='user_f_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spartakiada.User_f'),
        ),
    ]
