# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0030_auto_20170425_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_f',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='depart_id',
        ),
    ]
