# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0033_participants_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='department',
        ),
    ]
